FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./app /usr/share/nginx/html/app
COPY ./bower_components /usr/share/nginx/html/bower_components
COPY ./partials /usr/share/nginx/html/partials
